title: "Ali Nikkhah "
author: "Ali Nikkhah"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false      # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", file: "CV.pdf", icon:"home"}
  - {title: "Online Certificates", url:"certificates.md"}
  - {title: "Honors", url:"honors.md"}
  - {title: "Projects", url:"projects.md"}
  - {title: "About Me", url:"about.md"}
  - {title: "Contact Me", url:"contact.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:alinikkhah.application@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/alinikkhah2001"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
